/* ==========================================================
   EMT-2 專業名詞解釋庫
   結構：window.EMT2_GLOSSARY[名詞] = {en:英文全名, zh:中文名, def:說明}
   程式會自動在重點整理與題目中標出這些名詞，點一下（或按右鍵）顯示說明。

   要自己加詞：照同樣格式加一行即可，不用改主程式。
   ========================================================== */
window.EMT2_GLOSSARY = {

/* ---- 體系與法規 ---- */
"EMS":{en:"Emergency Medical Services",zh:"緊急醫療救護",
  def:"院前緊急醫療救護的整體系統，涵蓋報案受理、派遣、現場處置、運送到交接醫院的完整流程。"},
"EMT":{en:"Emergency Medical Technician",zh:"救護技術員",
  def:"我國分為初級、中級、高級三級，證書效期皆為 3 年，各級可施行的救護項目由《救護技術員管理辦法》明定。"},
"EMT-1":{en:"EMT-Basic",zh:"初級救護技術員",
  def:"初訓 56 小時，3 年內須完成 24 小時繼續教育。不得施行靜脈與骨內注射。"},
"EMT-2":{en:"EMT-Intermediate",zh:"中級救護技術員",
  def:"初訓 336 小時，3 年內須完成 72 小時繼續教育。可施行 IV、IO、SGA、EtCO2 監測，並協助使用病人自備藥物。"},
"EMT-P":{en:"EMT-Paramedic",zh:"高級救護技術員",
  def:"初訓 1296 小時，可執行氣管內管插管、針刺胸部減壓與給予多種急救藥物。"},
"MCI":{en:"Mass Casualty Incident",zh:"大量傷病患事件",
  def:"單一事故傷病患達 15 人以上，或預判可能達 15 人以上。核心原則是以有限資源救治最多的人。"},
"DOA":{en:"Dead on Arrival",zh:"明顯死亡",
  def:"須同時無意識、無呼吸、無脈搏，且具備屍腐、屍僵、焦黑、無首、內臟外溢、軀幹斷肢六者之一，方可不予送醫。",
  note:"六徵象具其一、且三無（意識/呼吸/脈搏）即可。低體溫為例外：僅『無首或屍僵』才可判定，其餘須先積極回溫。"},
"TTAS":{en:"Taiwan Triage and Acuity Scale",zh:"急診五級檢傷分類",
  def:"第一級復甦急救須立即處置，第二級危急 10 分鐘，第三級緊急 30 分鐘，第四級次緊急 60 分鐘，第五級非緊急 120 分鐘。",
  note:"到院前『危急個案』對應院內第 1、2 級。各級最久候診：2 級 10 分、3 級 30 分、4 級 60 分、5 級 120 分。"},

/* ---- 評估 ---- */
"GCS":{en:"Glasgow Coma Scale",zh:"格拉斯哥昏迷指數",
  def:"由張眼 E（4 分）、語言 V（5 分）、運動 M（6 分）組成，最低 3 分最高 15 分。8 分以下為重度昏迷。",
  note:"運動反應 M 最具預後價值。外傷病患 GCS < 9 應例行置入輔助呼吸道以防延遲性腦傷；GCS ≤ 8 為重度昏迷。"},
"AVPU":{en:"Alert, Verbal, Pain, Unresponsive",zh:"意識快速分級",
  def:"A 清醒、V 對聲音有反應、P 對痛刺激有反應、U 完全無反應。痛刺激用按指甲床或捏斜方肌，嚴禁搓胸骨。"},
"CRT":{en:"Capillary Refill Time",zh:"微血管充填時間",
  def:"按壓指甲床放開後恢復血色所需時間。超過 2 秒代表末梢灌流不良。"},
"SpO2":{en:"Peripheral Oxygen Saturation",zh:"血氧飽和度",
  def:"正常為 94% 以上。一氧化碳中毒時數值會偽性偏高，塗指甲油、末梢冰冷也會失準。"},
"EtCO2":{en:"End-tidal Carbon Dioxide",zh:"潮氣末二氧化碳",
  def:"CPR 時低於 10 mmHg 代表按壓品質不佳；突然躍升到 35 至 40 以上是恢復自發循環的徵兆；歸零代表氣道脫落。",
  note:"<10 代表按壓品質不佳要加強；驟升並維持 ≥40 疑 ROSC；歸零或波形消失先查氣道是否脫落。"},
"OPQRST":{en:"Onset, Provocation, Quality, Radiation, Severity, Time",zh:"疼痛病史詢問",
  def:"發作情形、加劇或緩解因子、疼痛性質、輻射部位、嚴重度、持續時間，常用於胸痛評估。"},
"XABCDE":{en:"",zh:"外傷評估流程",
  def:"大量外出血、呼吸道、呼吸、循環、神經學、暴露與保暖。與內科評估最大的差別是把止血放在第一位。"},
"PAT":{en:"Pediatric Assessment Triangle",zh:"小兒評估三角",
  def:"外觀、呼吸作功、皮膚循環三個維度，於接觸病童前 30 至 60 秒以視診與聽診完成。"},
"START":{en:"Simple Triage And Rapid Treatment",zh:"成人簡易檢傷法",
  def:"依能否行走、呼吸、循環、意識四關卡分出紅黃綠黑。任一項異常即列紅色。",
  note:"第一關能自行走動即綠色；呼吸 >30、橈脈摸不到或 CRT≥2 秒、不能遵從指令，任一即紅色。"},
"JumpSTART":{en:"",zh:"小兒簡易檢傷法",
  def:"用於 1 至 8 歲兒童。無呼吸但有脈搏時先給 5 次人工呼吸；呼吸標準改為每分鐘 15 至 45 次。",
  note:"與 START 最大不同：無呼吸但有脈搏時先給 5 次人工呼吸再判定（此為 JumpSTART 國際標準；課本僅載適用 1~8 歲）。"},
"CPSS":{en:"Cincinnati Prehospital Stroke Scale",zh:"辛辛那提中風指標",
  def:"臉部下垂、雙手平舉單側下垂、說話咬字不清，三項任一異常即懷疑中風。"},
"G-FAST":{en:"Gaze, Face, Arms, Speech, Time",zh:"大血管阻塞中風評估",
  def:"在 CPSS 之外加入凝視偏移。四項中三項以上異常高度提示大血管阻塞，應送有取栓能力的醫院。"},
"LKN":{en:"Last Known Normal",zh:"最後已知正常時間",
  def:"中風後送最關鍵的時間點。睡醒才發現的中風，須以入睡前最後正常的時刻計算。"},
"LVO":{en:"Large Vessel Occlusion",zh:"大血管阻塞",
  def:"腦部大動脈被血栓堵住，症狀嚴重，需動脈內取栓治療，發作 24 小時內仍有機會。"},
"EVT":{en:"Endovascular Thrombectomy",zh:"動脈內取栓術",
  def:"以導管自動脈取出血栓的治療，只有特定等級的急救責任醫院具備。"},

/* ---- 急救技術 ---- */
"CPR":{en:"Cardiopulmonary Resuscitation",zh:"心肺復甦術",
  def:"成人按壓深度 5 至 6 公分，速率每分鐘 100 至 120 次，壓吹比 30 比 2。",
  note:"嬰兒（未滿 1 歲）雙人施救改壓吹 15:2、雙拇指環抱；深度嬰兒約 4 cm、兒童約 5 cm，成人 5–6 cm。"},
"AED":{en:"Automated External Defibrillator",zh:"自動體外去顫器",
  def:"貼片貼右鎖骨下與左乳頭外側下方。電擊後立即接續按壓 2 分鐘，不可停下來量脈搏。",
  note:"電擊後立即接續 2 分鐘 CPR，不停下量脈搏。低體溫者電擊 1 次無效則暫緩，待核心 >30℃ 再續去顫。"},
"OHCA":{en:"Out-of-Hospital Cardiac Arrest",zh:"到院前心跳停止",
  def:"成人多為心因性，著重早期去顫；小兒多為窒息導致，最重要的是預防。",
  note:"生存之鏈前四環屬 EMS。建立 SGA 後接 EtCO₂ 監測按壓品質與 ROSC；機械按壓（LUCAS）用於長時間／人手不足／行進間。"},
"ROSC":{en:"Return of Spontaneous Circulation",zh:"恢復自發性循環",
  def:"心跳與血液循環恢復。EtCO2 突然躍升是重要徵兆。"},
"BVM":{en:"Bag-Valve-Mask",zh:"袋瓣罩甦醒球",
  def:"接 15 L/min 氧氣與儲氣袋可提供接近 100% 氧氣。擠壓約球體三分之一，見胸部起伏即可，切忌過度通氣。"},
"OPA":{en:"Oropharyngeal Airway",zh:"口咽呼吸道",
  def:"用於深昏迷且無嘔吐反射者。長度量嘴角到耳垂，凹面朝上推至硬顎後旋轉 180 度。"},
"NPA":{en:"Nasopharyngeal Airway",zh:"鼻咽呼吸道",
  def:"用於意識不清但仍有嘔吐反射者。長度量鼻尖到耳垂。疑似顱底骨折時絕對禁用。"},
"SGA":{en:"Supraglottic Airway",zh:"聲門上呼吸道",
  def:"如 LMA 與 i-gel，中級救護技術員可使用。需對痛刺激無反應且張口度達兩指幅以上。"},
"NRM":{en:"Non-Rebreather Mask",zh:"非再吸入型面罩",
  def:"流量 10 至 15 L/min，提供 80 至 100% 氧氣。儲氣袋須先充飽且吸氣時不塌陷。"},
"IV":{en:"Intravenous",zh:"靜脈注射",
  def:"中級救護技術員可施行。創傷大失血首選 18G 綠色針，內科急症常用 20G 粉紅色針。"},
"IO":{en:"Intraosseous",zh:"骨內注射",
  def:"90 秒內無法建立靜脈路徑時使用。成人首選肱骨近端與脛骨近端，置入後須以生理食鹽水快速沖洗骨髓腔。",
  note:"周邊靜脈 90 秒內（或兩次）建立失敗即改 IO。成人首選肱骨近端／脛骨近端，置入後以生理食鹽水快速沖洗。"},
"SMR":{en:"Spinal Motion Restriction",zh:"脊椎減移",
  def:"限制頭頸與脊椎活動以免二次傷害。可依加拿大頸椎規則三步驟評估是否能安全排除。"},
"KED":{en:"Kendrick Extrication Device",zh:"車內脫困器材",
  def:"固定順序為上頸圈、置入器材、胸腹固定帶（中下上）、鼠蹊帶、頸後填墊、頭部固定帶。"},
"CAT":{en:"Combat Application Tourniquet",zh:"戰術止血帶",
  def:"綁在傷口近心端 5 至 8 公分處，旋緊到出血停止且遠端脈搏消失，並記錄施打時間。",
  note:"到院前止血帶不可任意鬆開；一條無效可在其近心端並排上第二條。位置不明時以『綁高綁緊』為原則。"},
"TXA":{en:"Tranexamic Acid",zh:"傳明酸",
  def:"抗纖維蛋白溶解的止血藥物，創傷大出血建議於受傷 3 小時內儘早給予。"},
"NTG":{en:"Nitroglycerin",zh:"硝化甘油",
  def:"舌下含片，每 5 分鐘一顆最多三顆。收縮壓低於 90、心率低於 50 或高於 100、近期服用 PDE-5 抑制劑者禁用。",
  note:"給藥前後都要量血壓。四禁：SBP<90、HR<50 或 >100、24h 威而鋼／48h 犀利士、NTG 過敏。"},
"EpiPen":{en:"Epinephrine Auto-Injector",zh:"腎上腺素自動注射筆",
  def:"用於過敏性休克，肌肉注射於大腿前外側，可隔著衣物施打，未改善時每 10 分鐘可追加。",
  note:"打大腿前外側股外側肌、可隔衣。留意二相反應可能數小時後再發作，務必送醫觀察。"},

/* ---- 疾病與臨床徵象 ---- */
"ACS":{en:"Acute Coronary Syndrome",zh:"急性冠心症",
  def:"冠狀動脈供血不足造成的胸痛症候群。女性、糖尿病患與長者常無典型胸痛。"},
"AMI":{en:"Acute Myocardial Infarction",zh:"急性心肌梗塞",
  def:"心肌因血流中斷而壞死。非典型表現包括上腹悶痛、噁心嘔吐、冒冷汗與虛弱無力。"},
"STEMI":{en:"ST-Elevation Myocardial Infarction",zh:"ST 段上升型心肌梗塞",
  def:"心電圖出現 ST 段上升，需儘速送往具心導管能力的醫院。"},
"COPD":{en:"Chronic Obstructive Pulmonary Disease",zh:"慢性阻塞性肺病",
  def:"慢性氣道阻塞，吐氣時常聽見哮鳴音，給氧須留意二氧化碳滯留。"},
"DKA":{en:"Diabetic Ketoacidosis",zh:"糖尿病酮酸中毒",
  def:"多見於第一型糖尿病。血糖約 300 至 600，呈現深快的庫斯莫爾氏呼吸並帶丙酮水果味。"},
"HHS":{en:"Hyperosmolar Hyperglycemic State",zh:"高滲透壓高血糖狀態",
  def:"多見於第二型糖尿病長者。血糖常超過 600，脫水極度嚴重，無水果味。"},
"TBI":{en:"Traumatic Brain Injury",zh:"外傷性腦損傷",
  def:"處置核心為維持血氧、維持收縮壓 110 以上、EtCO2 維持 35 至 40，避免過度通氣。",
  note:"顧血壓（SBP>110，或維持 100–110）、EtCO₂ 35–40 勿過度換氣、床頭抬高 30°；警惕庫欣三徵：血壓高、心跳慢、呼吸不規則。"},
"ICP":{en:"Intracranial Pressure",zh:"顱內壓",
  def:"腦組織腫脹或出血造成壓力上升，可能壓迫腦幹形成腦疝脫。"},
"CPP":{en:"Cerebral Perfusion Pressure",zh:"腦灌流壓",
  def:"等於平均動脈壓減去顱內壓。腦傷病患須維持足夠血壓才能保住腦部灌流。"},
"EDH":{en:"Epidural Hematoma",zh:"硬腦膜上出血",
  def:"多為中硬腦膜動脈破裂，影像呈凸透鏡形，具典型的清明期。"},
"SDH":{en:"Subdural Hematoma",zh:"硬腦膜下出血",
  def:"大腦皮質橋靜脈破裂，影像呈新月形，長者與酗酒者輕微撞擊即可能發生。"},
"VF":{en:"Ventricular Fibrillation",zh:"心室顫動",
  def:"心室無效顫動導致無血液輸出，是可電擊心律，須立即去顫。"},
"Stridor":{en:"Stridor",zh:"喘鳴音",
  def:"吸氣時的高音調粗糙音，代表上呼吸道阻塞，如喉頭水腫、異物或哮吼。"},
"Wheezing":{en:"Wheezing",zh:"哮鳴音",
  def:"吐氣時的高音調哨音，代表下呼吸道痙攣狹窄，如氣喘、COPD、過敏性休克。"},
"Kussmaul":{en:"Kussmaul Breathing",zh:"庫斯莫爾氏呼吸",
  def:"深而快的過度換氣，是代謝性酸中毒（如糖尿病酮酸中毒）的呼吸性代償。"},
"Agonal":{en:"Agonal Gasping",zh:"瀕死喘息式呼吸",
  def:"極慢、微弱且不規則的喘息，是心跳停止初期的反射，不是有效呼吸，應立即開始 CPR。"},
"Beck":{en:"Beck's Triad",zh:"貝克氏三聯徵",
  def:"低血壓、頸靜脈怒張、心音遙遠沉悶，是心包填塞的典型表現。"},
"Kehr":{en:"Kehr's Sign",zh:"克爾氏徵象",
  def:"脾臟破裂導致橫膈受刺激，出現左肩轉移痛。"},
"Battle":{en:"Battle's Sign",zh:"巴氏徵候",
  def:"耳後乳突處瘀斑，提示中顱底或後顱底骨折。"},
"Anisocoria":{en:"Anisocoria",zh:"瞳孔不等大",
  def:"兩側瞳孔直徑相差 1 mm 以上，常提示顱內出血或腦疝脫壓迫動眼神經。"},
"Anhedonia":{en:"Anhedonia",zh:"失樂症",
  def:"對過去喜愛的事物失去興趣、無法感到快樂，是重度憂鬱症的核心指標之一。"},

/* ---- 特殊情境 ---- */
"TECC":{en:"Tactical Emergency Casualty Care",zh:"戰術緊急傷患救護",
  def:"由軍用 TCCC 轉化而來的民間版本，分為熱區、暖區、冷區三個照護階段。"},
"TCCC":{en:"Tactical Combat Casualty Care",zh:"戰術戰鬥傷患救護",
  def:"美軍依戰場實證發展的傷患救護準則，是 TECC 的前身。"},
"MARCH":{en:"",zh:"戰術創傷評估法",
  def:"大出血、呼吸道、呼吸、循環、低體溫與頭部外傷。用於暖區的系統性處置順序。",
  note:"熱區只做止血帶（綁高綁緊），嚴禁 CPR／插管／脫防護；退到暖區才走完整 MARCH。"},
"PACE":{en:"Primary, Alternate, Contingency, Emergency",zh:"撤退計畫四層備案",
  def:"主要方案、次要備援、應急方案、緊急極限方案，確保後送不中斷。"},
"AMS":{en:"Acute Mountain Sickness",zh:"急性高山症",
  def:"抵達海拔 2500 公尺以上後出現頭痛，並合併食慾差、疲憊、頭暈或失眠其中一項。"},
"HACE":{en:"High Altitude Cerebral Edema",zh:"高海拔腦水腫",
  def:"出現步態不穩的共濟失調與意識改變，最有效的處置是立即下降高度。"},
"HAPE":{en:"High Altitude Pulmonary Edema",zh:"高海拔肺水腫",
  def:"休息時仍嚴重呼吸困難、咳粉紅色泡沫痰。唯一根本處置是立即下撤 500 至 1000 公尺。"},
"DCS":{en:"Decompression Sickness",zh:"減壓病",
  def:"俗稱潛水夫病。上升過快使溶於體內的氮氣形成氣泡造成栓塞，需高壓氧艙再加壓治療。"},
"PPE":{en:"Personal Protective Equipment",zh:"個人防護裝備",
  def:"化災分為 A 至 D 四級。A 級為全罩氣密抗化衣加自攜式呼吸器，D 級為一般工作服。"},
"SCBA":{en:"Self-Contained Breathing Apparatus",zh:"自攜式空氣呼吸器",
  def:"提供最高等級的呼吸防護，缺氧環境（氧氣低於 19.5%）必須使用，濾毒罐無效。"},
"IDLH":{en:"Immediately Dangerous to Life or Health",zh:"立即致死致病濃度",
  def:"暴露即可能造成死亡或不可逆健康傷害的濃度，須使用 A 級或 B 級防護。"},
"ERG":{en:"Emergency Response Guidebook",zh:"緊急應變指南",
  def:"黃頁查聯合國編號、藍頁查英文名、紫頁查中文名、橘頁為處置指引、綠頁為隔離距離表。"},
"ALARA":{en:"As Low As Reasonably Achievable",zh:"合理抑低原則",
  def:"輻射防護的基本原則，配合時間、距離、屏蔽三大要領把劑量降到合理可行的最低。"},
"PEP":{en:"Post-Exposure Prophylaxis",zh:"暴露後預防性投藥",
  def:"針扎或體液暴觸後，經醫師評估須於 72 小時內儘速投藥。"},
"PTSD":{en:"Post-Traumatic Stress Disorder",zh:"創傷後壓力症候群",
  def:"三大症狀群為經驗重現、逃避與麻木、過度警覺。可善用員工協助方案與同儕支持。"},
"CIT":{en:"Crisis Intervention Team",zh:"危機處理小組",
  def:"1987 年起源於美國孟菲斯，訓練第一線人員以降級溝通技巧處理社區精神健康危機。"},
"TRM":{en:"Team Resource Management",zh:"團隊資源管理",
  def:"源自航空業的機組資源管理，四大模組為領導、溝通、守望、相助。"},
"ISBAR":{en:"Introduction, Situation, Background, Assessment, Recommendation",zh:"結構化交班",
  def:"自我介紹、目前情況、病患背景、評估結果、處置與建議。"},
"IMIST":{en:"Identification, Mechanism, Injury, Signs, Treatment",zh:"創傷交班模組",
  def:"身分、傷害機轉、受傷型態、症狀與生命徵象、已施行的處置。"},
"IMSAFE":{en:"Illness, Medication, Stress, Alcohol, Fatigue, Eating",zh:"人員狀態自我檢核",
  def:"生病、用藥、壓力、酒精、疲勞、飲食排泄。出勤前用來評估自己與隊友的身心狀態。"},
"METHANE":{en:"",zh:"災難標準通報口訣",
  def:"宣告重大事故、精確地點、災害類型、危害因子、進出動線、傷亡人數、請求支援單位。"},
"ICS":{en:"Incident Command System",zh:"事故指揮體系",
  def:"指揮官之下設安全官、聯絡官、新聞官，以及執行、計畫、後勤、財務四大部門。"},
"CUS":{en:"Concerned, Uncomfortable, Safety",zh:"階梯式關鍵字",
  def:"我感到擔憂、我感到不安、這有安全疑慮。用於安全關切未被採納時逐級升高表達。"},

/* ---- 到院前五級檢傷（首要／次要調節變數） ---- */
"五級檢傷":{en:"Five-level Triage",zh:"五級檢傷分級",
  def:"依病情危急度分五級：一級急救復甦（現場無法穩定須立即急救）、二級危急（需急救才能穩定或短時間會快速惡化）、三級緊急（穩定但會影響日常活動）、四級次緊急（穩定、不影響日常活動但需醫療處置）、五級非緊急（僅欲就醫）。到院前『危急個案』對應一、二級。"},
"首要調節變數":{en:"Primary Modifiers",zh:"首要調節變數",
  def:"檢傷最優先使用的六項評估：呼吸、血行動力、意識、體溫、疼痛程度、受傷機轉。通則為重度→一級、中度→二級、輕度→三級。首要優先於次要，最終取判定之最高級。"},
"次要調節變數":{en:"Secondary Modifiers",zh:"次要調節變數",
  def:"補充首要變數之判級，在基準備註欄以星號（*）標記。含①凝血機能異常與出血 ②對首要之補充（血糖<60或>324、高血壓急症SBP≧200/DBP≧110、脫水）③被選定者（胸痛、中風症狀、吞嚥困難、肢體外傷）④特定主訴（懷孕>20週、心理健康）。"},
"危急個案":{en:"Critical Case",zh:"危急個案",
  def:"依單項技術『病情危急度判斷』符合者即初判為檢傷一或二級。生命徵象門檻：GCS<14、呼吸≧30或<10、脈搏>150或<50、SBP>220或<90、CRT>2秒、體溫>41或<32℃、SpO₂<90%；另含高危外傷部位、高能量機轉與特殊情況。對應急診TTAS第一、二級。"},


/* ==== 追加：課本專有名詞（第二批） ==== */
"ALS":{en:"Advanced Life Support",zh:"高級救命術",
  def:"進階救命術，含氣管內插管、給藥、心律判讀與去顫，屬高級救護技術員(EMT-P)範疇。"},
"BLS":{en:"Basic Life Support",zh:"基本救命術",
  def:"基本維生救護：暢通呼吸道、人工呼吸、胸外按壓與 AED 去顫，是所有救護的基礎。"},
"PEA":{en:"Pulseless Electrical Activity",zh:"無脈性電氣活動",
  def:"心電圖有電氣活動卻摸不到脈搏、心臟無法有效泵血；屬非電擊心律，須持續 CPR 並找可逆病因。",
  note:"與心搏停止一樣屬不電擊心律；重點是持續高品質 CPR 並找可逆病因（如張力性氣胸、低血容）。"},
"NSTEMI":{en:"Non-ST-Elevation Myocardial Infarction",zh:"非 ST 上升型心肌梗塞",
  def:"心肌梗塞但心電圖無 ST 段上升，仍屬急性冠心症，須監測並後送。"},
"SI":{en:"Shock Index",zh:"休克指數",
  def:"每分鐘心率 ÷ 收縮壓；數值 > 1 即應懷疑休克。",
  note:"到院前可快速估休克：心率＞收縮壓（SI>1）即警覺，早期代償期血壓仍可能正常。"},
"MAP":{en:"Mean Arterial Pressure",zh:"平均動脈壓",
  def:"平均灌流壓，低於 65 mmHg 提示灌流不足；腦灌流壓 CPP = MAP − ICP。",
  note:"MAP<65 提示灌流不足。腦傷病患要維持足夠 MAP 以保住腦灌流壓（CPP=MAP−ICP）。"},
"SBP":{en:"Systolic Blood Pressure",zh:"收縮壓",
  def:"心臟收縮時的動脈壓；到院前休克常以 SBP < 90 為警戒。"},
"DBP":{en:"Diastolic Blood Pressure",zh:"舒張壓",
  def:"心臟舒張時的動脈壓；高血壓急症門檻 DBP ≧ 110。"},
"MCPR":{en:"Mechanical CPR Device",zh:"自動心肺復甦機",
  def:"機械式胸外按壓裝置(如 LUCAS)，用於長時間 CPR、人手不足或行進間，維持穩定按壓。"},
"DNR":{en:"Do Not Resuscitate",zh:"不施行心肺復甦術",
  def:"病人預立之拒絕心肺復甦或維生醫療同意書；不可為確認 DNR 與否而延誤該做的急救。"},
"ECPR":{en:"ECMO-assisted CPR",zh:"體外心肺復甦",
  def:"對特定可電擊、有旁觀者 CPR、無明顯外傷之心停者，以葉克膜輔助之進階復甦。"},
"CardiogenicShock":{en:"Cardiogenic Shock",zh:"心因性休克",
  def:"心肌梗塞、嚴重心律不整或心衰致心輸出量不足所引起的休克。"},
"HypovolemicShock":{en:"Hypovolemic Shock",zh:"血容不足性休克",
  def:"因出血或脫水使循環血量不足所致，外傷失血最常見。"},
"ObstructiveShock":{en:"Obstructive Shock",zh:"阻塞性休克",
  def:"心臟輸血過程受阻，如心包填塞、張力性氣胸、肺栓塞。"},
"DistributiveShock":{en:"Distributive Shock",zh:"分佈性休克",
  def:"血管異常擴張使血液分佈不當，含過敏性、敗血性、神經性休克。"},
"OpenPneumothorax":{en:"Open Pneumothorax",zh:"開放性氣胸",
  def:"胸壁穿透傷使空氣隨呼吸進出胸腔(吸吮性傷口)；用具導氣孔胸封貼片，或三邊固定。"},
"TensionPneumothorax":{en:"Tension Pneumothorax",zh:"張力性氣胸",
  def:"胸腔空氣只進不出壓迫縱膈；呼吸窘迫、單側呼吸音消失、頸靜脈怒張，需針刺減壓。",
  note:"三大警訊：呼吸窘迫、患側呼吸音消失、頸靜脈怒張（＋氣管偏移）。屬阻塞性休克，需針刺減壓。"},
"Hemothorax":{en:"Hemothorax",zh:"血胸",
  def:"胸腔內積血，可致失血性休克與呼吸受限。"},
"FlailChest":{en:"Flail Chest",zh:"連枷胸",
  def:"相鄰兩根以上肋骨各斷至少兩處，形成游離胸壁段，呈與呼吸相反的奇異運動。"},
"Tamponade":{en:"Cardiac Tamponade",zh:"心包填塞",
  def:"心包腔積液壓迫心臟；典型貝克三徵：低血壓、頸靜脈怒張、心音遙遠沉悶。"},
"SubcutaneousEmphysema":{en:"Subcutaneous Emphysema",zh:"皮下氣腫",
  def:"皮下組織積氣、觸診有捻髮感，提示氣管或肺部損傷。"},
"Dyspnea":{en:"Dyspnea",zh:"呼吸困難",
  def:"病人主觀感覺呼吸費力、不適、無力或窒息感。"},
"Tachypnea":{en:"Tachypnea",zh:"呼吸急促",
  def:"呼吸速率增加，每分鐘大於 20 次。"},
"Bradypnea":{en:"Bradypnea",zh:"呼吸徐緩",
  def:"呼吸速率減少，每分鐘小於 10 次。"},
"Hyperventilation":{en:"Hyperventilation",zh:"過度換氣",
  def:"規則而加快的深呼吸，常見於代謝性酸中毒代償、缺氧或焦慮。"},
"TidalVolume":{en:"Tidal Volume",zh:"潮氣量",
  def:"一次平靜呼吸進出的空氣量，正常成人約 300～700 mL（6～8 mL/kg）。"},
"Capnography":{en:"Capnography",zh:"二氧化碳圖儀",
  def:"監測潮氣末二氧化碳(EtCO₂)波形與數值，用於確認進階呼吸道位置與 CPR 品質。"},
"NasalCannula":{en:"Nasal Cannula",zh:"鼻導管",
  def:"流量 1～6 L/min，氧氣濃度約 24～44%；適用呼吸緩和、非張口呼吸者。",
  note:"給氧三件套速記：鼻導管 1–6 L(24–44%)、簡單面罩 6–10 L(40–60%)、非再吸入面罩 10–15 L(80–100%)。"},
"SimpleMask":{en:"Simple Face Mask",zh:"簡單型面罩",
  def:"流量 6～10 L/min，氧氣濃度約 40～60%；適用張口呼吸、呼吸稍快者。"},
"NRS":{en:"Numerical Rating Scale",zh:"數字疼痛評定量表",
  def:"0 分不痛、10 分最痛，用於 ≥9 歲；3～8 歲改用臉譜量表。"},
"WongBaker":{en:"Wong-Baker FACES Pain Scale",zh:"臉譜疼痛量表",
  def:"以臉譜結合數字評估疼痛，適用 3～8 歲兒童。"},
"CanadianCSpine":{en:"Canadian C-Spine Rule",zh:"加拿大頸椎規則",
  def:"以高危因子、低危因子、能否主動左右轉頭 45° 三步驟，判斷可否安全排除脊椎減移。",
  note:"三步驟任一未過即需 SMR：①有高危因子②不具低危因子③無法主動左右轉頭 45°。"},
"LoadAndGo":{en:"Load and Go",zh:"載了就走",
  def:"危急個案於現場僅做必要穩定即快速後送的策略。"},
"StayAndPlay":{en:"Stay and Play",zh:"現場穩定後送",
  def:"病情許可時於現場穩定生命徵象後再運送的策略。"},
"HeatCramps":{en:"Heat Cramps",zh:"熱痙攣",
  def:"熱天劇烈運動後疼痛性肌肉抽筋，體溫正常，補充水分與電解質。"},
"HeatExhaustion":{en:"Heat Exhaustion",zh:"熱衰竭",
  def:"高溫大量排汗致脫水，體溫多在 40°C 以下、意識清醒；移至陰涼並補液。"},
"HeatStroke":{en:"Heat Stroke",zh:"熱中暑",
  def:"中樞體溫 > 40°C 併中樞神經功能障礙，死亡率高，須先快速降溫再送醫。",
  note:"與熱衰竭最大差別＝中樞體溫>40℃＋意識/中樞神經異常。原則『先降溫再送』，冰水浸泡最快。"},
"Frostbite":{en:"Frostbite",zh:"凍瘡",
  def:"低溫造成局部組織細胞損傷壞死；浸泡 37～39°C 溫水回溫，勿火烤或摩擦，保留水泡。"},
"Frostnip":{en:"Frostnip",zh:"凍傷",
  def:"皮膚表面形成冰晶、傷害尚可逆轉的輕度冷傷害。"},
"HIV":{en:"Human Immunodeficiency Virus",zh:"人類免疫缺乏病毒",
  def:"血液/體液傳播病原；針扎暴觸後經醫師評估須於 72 小時內考慮暴露後預防投藥(PEP)。"},
"HBV":{en:"Hepatitis B Virus",zh:"B 型肝炎病毒",
  def:"血液傳播病原，EMT 針扎主要風險之一。"},
"HCV":{en:"Hepatitis C Virus",zh:"C 型肝炎病毒",
  def:"血液或體液傳播病原之一。"},
"StandardPrecautions":{en:"Standard Precautions",zh:"標準防護措施",
  def:"視所有病人血液體液皆具傳染性，一律採手套、洗手、口罩與護目等防護。",
  note:"核心＝視所有體液具傳染性。針扎後：擠出血、清水沖、通報，並於 72 小時內評估 PEP。"},
"TOCC":{en:"Travel, Occupation, Contact, Cluster",zh:"傳染病接觸史問診",
  def:"問診旅遊史、職業史、接觸史與群聚史，用於評估傳染病風險。"},
"EMSS":{en:"Emergency Medical Service System",zh:"緊急醫療救護體系",
  def:"整合報案受理、派遣、到院前救護與醫院的完整系統。"},
"EMD":{en:"Emergency Medical Dispatch",zh:"緊急醫療派遣",
  def:"派遣中心辨識危急個案並給予線上指導，可減少非必要的緊急駕駛。"},
"CRM":{en:"Crew Resource Management",zh:"機組資源管理",
  def:"源自航空業，改善人員溝通合作、減少人為錯誤，是團隊資源管理(TRM)的前身。"},
"PHTLS":{en:"Prehospital Trauma Life Support",zh:"到院前創傷救命術",
  def:"到院前外傷評估與處置的系統化訓練課程。"},
"EAP":{en:"Employee Assistance Program",zh:"員工協助方案",
  def:"提供 EMS 人員心理支持與壓力調適資源，用於創傷後壓力(PTSD)等預防。"},
"MEDEVAC":{en:"Medical Evacuation",zh:"醫療後送",
  def:"以直升機或載具將傷病患後送至醫療機構。"},


/* ==== 追加：課本專有名詞（第三批） ==== */
"Orthopnea":{en:"Orthopnea",zh:"端坐呼吸",
  def:"平躺時呼吸困難、需坐起或墊高才能呼吸，常見於心臟衰竭、肺水腫。"},
"Hyperpnea":{en:"Hyperpnea",zh:"呼吸過深",
  def:"呼吸深度增加（速率可正常），見於代謝需求增加或酸中毒代償。"},
"CoreBodyTemperature":{en:"Core Body Temperature",zh:"核心體溫",
  def:"身體內部（耳、直腸、食道）溫度，正常約 37°C，較能反映真實體溫。"},
"ShellTemperature":{en:"Shell Temperature",zh:"體表溫度",
  def:"皮膚與四肢表層溫度，易受環境影響。"},
"Hyperthermia":{en:"Hyperthermia",zh:"體溫過高",
  def:"產熱大於散熱使核心體溫升高，如熱急症。"},
"Hypothermia":{en:"Hypothermia",zh:"體溫過低",
  def:"核心體溫低於 35°C。"},
"PinpointPupils":{en:"Pinpoint Pupils",zh:"針狀瞳孔",
  def:"兩側瞳孔極度縮小，見於鴉片類中毒、有機磷中毒、橋腦出血。"},
"PosturalHypotension":{en:"Postural Hypotension",zh:"姿勢性低血壓",
  def:"由臥到站時收縮壓明顯下降並頭暈；長者、脫水、失血常見。"},
"Contusion":{en:"Contusion",zh:"挫傷",
  def:"鈍力致皮下組織與微血管破裂、無開放傷口的瘀傷。"},
"Hematoma":{en:"Hematoma",zh:"皮下血腫",
  def:"血液積聚於組織形成的腫塊。"},
"Abrasion":{en:"Abrasion",zh:"擦傷",
  def:"表皮被摩擦刮除的淺層傷口。"},
"Laceration":{en:"Laceration",zh:"撕裂傷",
  def:"皮膚被撕裂、傷緣不規則的開放傷口。"},
"IncisedWound":{en:"Incised / Cutting Wound",zh:"切割傷",
  def:"銳器造成、傷緣整齊的開放傷口。"},
"PenetratingWound":{en:"Penetrating Wound",zh:"穿刺傷",
  def:"尖銳物穿入體內，傷口小但可能深部受損。"},
"Avulsion":{en:"Avulsion",zh:"剝離傷",
  def:"皮膚或組織被撕脫、部分或完全離斷。"},
"Rhinorrhea":{en:"Rhinorrhea",zh:"腦脊髓液鼻漏",
  def:"腦脊髓液自鼻流出，顱底骨折徵象之一。"},
"Otorrhea":{en:"Otorrhea",zh:"腦脊髓液耳漏",
  def:"腦脊髓液自耳流出，顱底骨折徵象之一。"},
"RaccoonEyes":{en:"Raccoon Eyes",zh:"浣熊眼",
  def:"兩側眼周瘀青，前顱窩顱底骨折徵象。"},
"MassiveHemothorax":{en:"Massive Hemothorax",zh:"大量血胸",
  def:"胸腔大量積血，可致失血性休克與呼吸窘迫。"},
"Angina":{en:"Angina Pectoris",zh:"心絞痛",
  def:"心肌缺氧引起的胸悶胸痛。"},
"UnstableAngina":{en:"Unstable Angina",zh:"不穩定型心絞痛",
  def:"休息或輕微活動即發作、型態惡化，屬急性冠心症。"},
"StableAngina":{en:"Stable Angina",zh:"穩定型心絞痛",
  def:"固定程度活動誘發，休息或含 NTG 可緩解。"},
"Arrhythmia":{en:"Arrhythmia",zh:"心律不整",
  def:"心臟節律或速率異常。"},
"AtrialFibrillation":{en:"Atrial Fibrillation",zh:"心房顫動",
  def:"常見不規則心律，增加中風風險。"},
"Atherosclerosis":{en:"Atherosclerosis",zh:"動脈粥狀硬化",
  def:"動脈壁脂肪斑塊沉積、管腔狹窄硬化。"},
"Aneurysm":{en:"Aneurysm",zh:"動脈瘤",
  def:"動脈壁局部異常膨出，破裂可致命。"},
"Fever":{en:"Fever",zh:"發燒",
  def:"體溫調節中樞設定點上移致中樞體溫升高（中樞 >38°C）。"},
"SARS":{en:"Severe Acute Respiratory Syndrome",zh:"嚴重急性呼吸道症候群",
  def:"冠狀病毒引起之高傳染性呼吸道疾病。"},
"MERS":{en:"Middle East Respiratory Syndrome",zh:"中東呼吸症候群",
  def:"冠狀病毒引起之呼吸道感染症。"},
"AIDS":{en:"Acquired Immunodeficiency Syndrome",zh:"後天免疫缺乏症候群",
  def:"HIV 感染晚期，免疫系統嚴重受損。"},
"Aerosol":{en:"Aerosol",zh:"飛沫微粒（氣溶膠）",
  def:"懸浮於空氣的微小顆粒，某些醫療處置會產生、增加空氣傳染風險。"},
"Anthrax":{en:"Anthrax",zh:"炭疽病",
  def:"炭疽桿菌引起，屬生物戰劑之一。"},
"Plague":{en:"Plague",zh:"鼠疫",
  def:"鼠疫桿菌引起，屬生物戰劑之一。"},
"Botulism":{en:"Botulism",zh:"肉毒桿菌中毒",
  def:"肉毒桿菌毒素引起之神經麻痺，屬生物戰劑之一。"},
"Peritonitis":{en:"Peritonitis",zh:"腹膜炎",
  def:"腹膜發炎，出現腹部僵硬、壓痛與反跳痛。"},
"Dysphagia":{en:"Dysphagia",zh:"吞嚥困難",
  def:"吞嚥不順或疼痛，中風等神經問題常見。"},
"NasogastricTube":{en:"Nasogastric Tube",zh:"鼻胃管",
  def:"經鼻置入胃部之管路，供灌食或引流減壓。"},
"UrinaryCatheter":{en:"Urinary Catheter",zh:"導尿管",
  def:"經尿道置入膀胱引流尿液之管路。"},
"TracheostomyTube":{en:"Tracheostomy Tube",zh:"氣切管",
  def:"氣管造口置入之呼吸管路。"},
"Stoma":{en:"Stoma",zh:"造口",
  def:"腸道或泌尿道經腹壁引出體外的開口。"},
"AVFistula":{en:"Arteriovenous Fistula",zh:"動靜脈瘻管",
  def:"洗腎用之動靜脈接通；該肢禁量血壓與抽血，觸診有震顫（Thrill）。"},
"Bruit":{en:"Bruit",zh:"血管雜音",
  def:"聽診血管時的異常雜音。"},
"PressureUlcer":{en:"Pressure Ulcer",zh:"壓瘡",
  def:"長期受壓致皮膚與皮下組織壞死（褥瘡）。"},
"SepticShock":{en:"Septic Shock",zh:"敗血性休克",
  def:"嚴重感染引起全身炎症、血管擴張與灌流不足（屬分佈性休克）。"},
"NeurogenicShock":{en:"Neurogenic Shock",zh:"神經性休克",
  def:"脊髓損傷致交感失調、血管擴張，心跳未代償變快（屬分佈性休克）。"},
"AnaphylacticShock":{en:"Anaphylactic Shock",zh:"過敏性休克",
  def:"嚴重過敏致血管擴張與呼吸道水腫，首選腎上腺素。"},
"BoylesLaw":{en:"Boyle's Law",zh:"波以耳定律",
  def:"定溫下氣體體積與壓力成反比，解釋潛水與空中救護的氣體膨脹。"},
"DaltonsLaw":{en:"Dalton's Law",zh:"道爾頓分壓定律",
  def:"混合氣體總壓為各氣體分壓之和，關係高海拔缺氧。"},
"Tetany":{en:"Tetany",zh:"僵直性痙攣",
  def:"持續肌肉痙攣僵直，見於低血鈣、電擊。"},
"Recompression":{en:"Recompression Therapy",zh:"再加壓治療",
  def:"減壓病送高壓氧艙再加壓治療。"},
"LLAMSS":{en:"Lake Louise AMS Score",zh:"路易斯湖高山症指數",
  def:"評估急性高山症嚴重度的量表。"},
"HPMK":{en:"Hypothermia Prevention & Management Kit",zh:"低體溫防護處置包",
  def:"戰術外傷用主動保溫裝備，防致死三聯症。"},
"AC":{en:"Alternating Current",zh:"交流電",
  def:"電流方向週期改變（家用電源），較易引起心室顫動與肌肉持續收縮。"},
"DC":{en:"Direct Current",zh:"直流電",
  def:"電流方向固定（如雷擊、電池），常造成單次強力肌肉收縮拋離。"},
"Gray":{en:"Gray (Gy)",zh:"戈雷",
  def:"輻射吸收劑量單位。"},
"Sievert":{en:"Sievert (Sv)",zh:"西弗",
  def:"輻射等效劑量單位，衡量對人體的危害。"},
"RadProtection":{en:"Time, Distance, Shielding",zh:"輻射防護三原則",
  def:"縮短暴露時間、拉開與射源距離、加強屏蔽。"},
"HAZMAT":{en:"Hazardous Materials Response",zh:"危害物質應變",
  def:"危害性化學物質事故之現場處置。"},
"GHS":{en:"Globally Harmonized System",zh:"化學品全球調和制度",
  def:"化學品危害分類與標示的國際統一系統。"},
"SDS":{en:"Safety Data Sheet",zh:"安全資料表",
  def:"化學品之危害、處置與急救資訊表（舊稱 MSDS）。"},
"TIH":{en:"Toxic Inhalation Hazard",zh:"吸入毒性危害物質",
  def:"吸入即具毒性之危害物質。"},
"ZoneControl":{en:"Hot / Warm / Cold Zone",zh:"三區管制",
  def:"化災或戰術現場依危害程度劃分熱區、暖區、冷區。"},
"Ipratropium":{en:"Ipratropium",zh:"異丙托溴銨",
  def:"抗膽鹼支氣管擴張劑，用於氣喘、COPD。"},
"Terbutaline":{en:"Terbutaline",zh:"特布他林",
  def:"β 促效支氣管擴張劑。"},
"DAI":{en:"Drug-Assisted Intubation",zh:"藥物輔助氣管插管",
  def:"以鎮靜等藥物輔助之氣管插管。"},
"SurgicalAirway":{en:"Surgical Airway",zh:"外科呼吸道",
  def:"如環甲膜切開術，外科方式建立呼吸道。"},
"SixP":{en:"Pain, Pallor, Pulselessness, Paresthesia, Paralysis, Poikilothermia",zh:"肢體缺血 6P",
  def:"疼痛、蒼白、無脈、感覺異常、麻痺、患肢冰冷；肢體缺血或腔室症候群警訊。"},
"CushingReflex":{en:"Cushing Reflex",zh:"庫欣反射（現象）",
  def:"顱內壓升高的反應：血壓升高、心跳變慢、呼吸型態改變（庫欣三徵）。"},
"PRICE":{en:"Protection, Rest, Ice, Compression, Elevation",zh:"軟組織傷處置",
  def:"保護、休息、冰敷、壓迫、抬高。"},
"TwoChallengeRule":{en:"Two-Challenge Rule",zh:"兩次質疑原則",
  def:"對可能危及安全的決策至少提出兩次關切，未獲回應即升級處理。"},
"ClosedLoop":{en:"Call-out / Check-back",zh:"閉環溝通",
  def:"以主動呼叫與回覆確認確保訊息正確接收。"},
"ATP":{en:"Adenosine Triphosphate",zh:"三磷酸腺苷",
  def:"細胞能量分子；缺氧時轉為無氧代謝、乳酸堆積。"}
};
